### ISSUE TITLE
Cannot find module 'rollup-plugin-vue'

### ISSUE THREAD

**Issue by deathmaz** [znck/rollup-plugin-vue#16]
Hi, thank you for your work.
I tried to use your plugin like this:
```js
// rollup.config.js 
import vue from 'rollup-plugin-vue'
import buble from 'rollup-plugin-buble'
 
export default {
  entry: './assets/js/main.js',
  plugins: [
    vue(),
    buble()
  ]
}
```
When i run `rollup -c` i'm getting the following:
```sh
Cannot find module 'rollup-plugin-vue'
Error: Cannot find module 'rollup-plugin-vue'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/rollup-vue/rollup.config.js:5:27)
    at Module._compile (module.js:556:32)
    at Object.require.extensions..js (/usr/lib/node_modules/rollup/bin/rollup:761:8)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```
To make it work i went to `/node_modules/rollup-plugin-vue` and launched `npm run build` there.

**Comment by znck** [comment]
Fixed in v2.2.1
